class AppStrings {
  static const Map<String, Map<String, String>> localizedStrings = {
    'English': {
      'app_title_hindi': 'हनुमान चालीसा',
      'app_title_english': 'Hanuman Chalisa',
      'start_reading': 'START READING',
      'listen_chalisa': 'LISTEN TO CHALISA',
      'language': 'Language',
      'intent': 'Intent',
      'settings': 'Settings',
      'settings_title': 'Settings',
      'reading_comfort': 'READING COMFORT',
      'text_size': 'Text Size',
      'app_language': 'App Language',
      'experience': 'EXPERIENCE',
      'show_meaning': 'Show Meaning',
      'background_sound': 'Background Sound',
      'temple_ambience': 'Temple Ambience',
      'made_with_devotion': 'MADE WITH DEVOTION',
      'completed': 'Completed',
      'welcome': 'Welcome / स्वागत',
      'choose_language':
          'Choose your preferred language\nअपनी पसंदीदा भाषा चुनें',
      'continue': 'Continue',
      'language_title': 'LANGUAGE',
      'choose_script': 'Choose your\nreading script',
      'begin_journey': 'Begin Journey',
      'hindi_devanagari': 'Hindi (Devanagari)',
      'original_script': 'Original sacred script',
      'hindi_meaning': 'Hindi + Meaning',
      'with_meaning': 'With English translation',
      'english_transliteration': 'English Transliteration',
      'phonetic_reading': 'Phonetic reading',
      'hanuman_chalisa_completed': 'Hanuman Chalisa Completed',
      'previous': 'PREVIOUS',
      'next': 'NEXT',
      'finish': 'FINISH',
      'swipe_to_start_reading': 'Swipe to start reading',
      'sit_quietly': 'Sit quietly for a moment.',
      'return_home': 'Return Home',
      'pause_here': 'Pause here.',
      'take_a_breath': 'Take a breath.',
      'resume': 'RESUME',
      'breathe_in': 'Breathe in...',
      'breathe_out': 'Breathe out...',
      'find_center': 'Find your center',
      'skip': 'SKIP',
      'intent_title': 'Our Intent',
      'intent_desc_1':
          'This app exists to provide a focused, calm space for reading the Hanuman Chalisa. In a world of distraction, we wanted to build a sanctuary for your practice.',
      'intent_desc_2':
          'There are no ads, no tracking, and no distractions. Just the verses and your devotion.',
      'chaupai': 'Chaupai',
      'doha': 'Doha',
      'singer_name': 'Hari Om Sharan',
    },
    'Hindi': {
      'app_title_hindi': 'हनुमान चालीसा',
      'app_title_english': 'Hanuman Chalisa',
      'start_reading': 'पाठ शुरू करें',
      'listen_chalisa': 'चालीसा सुनें',
      'language': 'भाषा',
      'intent': 'संकल्प',
      'settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स',
      'reading_comfort': 'पठन सुविधा',
      'text_size': 'अक्षर का आकार',
      'app_language': 'ऐप भाषा',
      'experience': 'अनुभव',
      'show_meaning': 'अर्थ दिखाएं',
      'background_sound': 'पार्श्व ध्वनि',
      'temple_ambience': 'मंदिर का वातावरण',
      'made_with_devotion': 'भक्ति के साथ निर्मित',
      'completed': 'पूर्ण',
      'welcome': 'स्वागत',
      'choose_language': 'अपनी पसंदीदा भाषा चुनें',
      'continue': 'आगे बढ़ें',
      'language_title': 'भाषा',
      'choose_script': 'अपनी पठन\nलिपि चुनें',
      'begin_journey': 'यात्रा शुरू करें',
      'hindi_devanagari': 'हिंदी (देवनागरी)',
      'original_script': 'मूल पवित्र लिपि',
      'hindi_meaning': 'हिंदी + अर्थ',
      'with_meaning': 'अंग्रेजी अनुवाद के साथ',
      'english_transliteration': 'अंग्रेजी लिप्यंतरण',
      'phonetic_reading': 'ध्वन्यात्मक पठन',
      'hanuman_chalisa_completed': 'हनुमान चालीसा पूर्ण हो गई',
      'previous': 'पिछला',
      'next': 'अगला',
      'finish': 'समाप्त',
      'swipe_to_start_reading': 'पढ़ना शुरू करने के लिए स्वाइप करें',
      'sit_quietly': 'एक पल के लिए शांति से बैठें।',
      'return_home': 'घर वापस आएं',
      'pause_here': 'यहाँ रुकें।',
      'take_a_breath': 'एक गहरी सांस लें।',
      'resume': 'जारी रखें',
      'breathe_in': 'सांस भरें...',
      'breathe_out': 'सांस छोड़ें...',
      'find_center': 'ध्यान् केंद्रित करें',
      'skip': 'छोड़ें',
      'intent_title': 'हमारा संकल्प',
      'intent_desc_1':
          'यह ऐप हनुमान चालीसा के पाठ के लिए एक केंद्रित और शांत स्थान प्रदान करने के लिए बनाया गया है। विकर्षणों की दुनिया में, हम आपकी साधना के लिए एक पवित्र स्थान बनाना चाहते थे।',
      'intent_desc_2':
          'इसमें कोई विज्ञापन नहीं, कोई ट्रैकिंग नहीं और कोई विकर्षण नहीं है। केवल श्लोक और आपकी भक्ति।',
      'chaupai': 'चौपाई',
      'doha': 'दोहा',
      'singer_name': 'हरि ओम शरण',
    },
  };

  static String get(String key, String languageCode) {
    return localizedStrings[languageCode]?[key] ??
        localizedStrings['English']![key]!;
  }
}
